name: Self publish extension on shared web host via FTP

on:
  push:
    tags:
      - 'v*'
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      WEB_EXT_API_KEY=${{ secrets.WEB_EXT_API_KEY }}
      WEB_EXT_API_SECRET=${{ secrets.WEB_EXT_API_SECRET }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: npm install
        run: npm install

      - name: run extension build process
        run: npm run build

      - name: run extension signing process
        run: npm run sign

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ${{ secrets.LOCAL_DIR }}
          server-dir: ${{ secrets.SERVER_DIR }}
          port: 21
